name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - name: Install stable toolchain
    - uses: actions-rs/toolchain@v1
    - name: Get latest checkout
    - uses: actions/checkout@v3
    - name: Update
    - run: rustup update ${{matrix.toolchain}} && rustup default ${{matrix.toolchain}}
    - name: Build
      run: cargo build --verbose
